import { apiBase, apiURL } from "./url";

const BASE = apiBase(process.env.NEXT_PUBLIC_CATALOGUE_API_BASE_URL ?? process.env.NEXT_PUBLIC_API_BASE_URL);
const TIMEOUT_MS = 15_000;
export type PublicFarmer = { id:string;name:string;farmName?:string;farmArea?:string;totalLandArea?:string;category?:string;subCategories:string[];seasonalCrops:string[];perennialCrops:string[];avatar?:string;farmImages:string[];about?:string;experienceDescription?:string;awards:string[];place?:string;district?:string;state?:string;irrigationType?:string;soilType?:string;waterSource?:string;farmingExperienceYears?:string;organicCertified:boolean;delivery:boolean;deliveryRadiusKm?:number;rating:number;reviewsCount:number;last30daysSales:number;verified:boolean;availableForOrders:boolean;createdAt?:string };
export type FarmerPage={items:PublicFarmer[];meta:{page:number;limit:number;total:number;totalPages:number}};
type FarmerProduct={id?:string;_id?:string;name:string;price?:number;image?:string;images?:string[]};
export class FarmerAPIError extends Error { constructor(message:string,readonly status:number,readonly code:string){super(message);this.name="FarmerAPIError"} }
async function get<T>(path:string,cache:RequestCache="no-store"):Promise<T>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),TIMEOUT_MS);try{const response=await fetch(apiURL(BASE,path),{headers:{Accept:"application/json"},cache,signal:controller.signal});let body:any;try{body=await response.json()}catch{throw new FarmerAPIError("Farmer service returned malformed JSON",response.status,"malformed_response")};if(!response.ok||body?.success!==true||body.data===undefined)throw new FarmerAPIError(body?.message??`Farmer request failed (${response.status})`,response.status,body?.code??"http_error");return body.data as T}catch(error){if(error instanceof FarmerAPIError)throw error;if(error instanceof Error&&error.name==="AbortError")throw new FarmerAPIError("Farmer service timed out",0,"timeout");throw new FarmerAPIError("Farmer service is unavailable",0,"unavailable")}finally{clearTimeout(timer)}}
export const farmerAPI={list(query:Record<string,string|number|undefined>={}):Promise<FarmerPage>{const p=new URLSearchParams();for(const[k,v]of Object.entries(query))if(v!==undefined&&v!=="")p.set(k,String(v));return get<FarmerPage>(`/farmers?${p}`)},get(id:string):Promise<PublicFarmer>{return get<PublicFarmer>(`/farmers/${encodeURIComponent(id)}`)},async products(id:string):Promise<FarmerProduct[]>{const data=await get<{items?:FarmerProduct[];products?:FarmerProduct[]}>(`/farmers/${encodeURIComponent(id)}/products`);return data.items??data.products??[]}};
