// app/(legal)/terms/page.tsx

export const metadata = {
  title: "Terms & Conditions | fr3sh.in",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gray-50">
      <div className="mx-auto max-w-3xl px-4 py-10">
        <header className="space-y-2 mb-8">
          <h1 className="text-3xl font-semibold tracking-tight">
            Terms &amp; Conditions
          </h1>
          <p className="text-sm text-gray-500">
            Last updated: 26 November 2025
          </p>
        </header>

        <div className="space-y-8 text-sm leading-relaxed">
          {/* 1. Electronic Record */}
          <section className="space-y-3">
            <p>
              This document is an electronic record in terms of the Information
              Technology Act, 2000 and rules thereunder as applicable and the
              amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures.
            </p>
          </section>

          {/* 2. Publication & Platform Definition */}
          <section className="space-y-3">
            <p>
              This document is published in accordance with the provisions of
              Rule 3(1) of the Information Technology (Intermediaries Guidelines)
              Rules, 2011 that require publishing the rules and regulations,
              privacy policy and Terms of Use for access or usage of domain name{" "}
              <a
                href="https://fr3sh.in/"
                className="text-blue-600 underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                https://fr3sh.in/
              </a>{" "}
              (&apos;Website&apos;), including the related mobile site and mobile
              application (hereinafter referred to as &apos;Platform&apos;).
            </p>

            <p>
              The Platform is owned by Varmtech, a company incorporated under
              the Companies Act, 1956 with its registered office at Door No
              405, Revenue Ward 5, Narayana Sanidhi Madhurawada, Madhurawada,
              Vishakhapatnam, India (hereinafter referred to as
              &quot;Platform Owner&quot;, &apos;we&apos;, &apos;us&apos;,
              &apos;our&apos;).
            </p>
          </section>

          {/* 3. Binding Nature of Terms */}
          <section className="space-y-3">
            <p>
              Your use of the Platform and services and tools are governed by
              the following terms and conditions (&quot;Terms of Use&quot;) as
              applicable to the Platform including the applicable policies which
              are incorporated herein by way of reference. If you transact on
              the Platform, you shall be subject to the policies that are
              applicable to the Platform for such transaction.
            </p>

            <p>
              By mere use of the Platform, you shall be contracting with the
              Platform Owner and these terms and conditions including the
              policies constitute your binding obligations with the Platform
              Owner. These Terms of Use relate to your use of our website, goods
              (as applicable) or services (as applicable) (collectively,
              &quot;Services&quot;). Any terms and conditions proposed by you
              which are in addition to or which conflict with these Terms of Use
              are expressly rejected by the Platform Owner and shall be of no
              force or effect. These Terms of Use can be modified at any time
              without assigning any reason. It is your responsibility to
              periodically review these Terms of Use to stay informed of
              updates.
            </p>

            <p>
              For the purpose of these Terms of Use, wherever the context so
              requires &quot;you&quot;, &quot;your&quot; or &quot;user&quot;
              shall mean any natural or legal person who has agreed to become a
              user/buyer on the Platform.
            </p>

            <p className="font-medium uppercase tracking-wide">
              ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR
              AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF
              USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
            </p>
          </section>

          {/* 4. General Use of Platform & Services */}
          <section className="space-y-3">
            <p>
              The use of the Platform and/or availing of our Services is subject
              to the following Terms of Use:
            </p>

            <p>
              To access and use the Services, you agree to provide true,
              accurate and complete information to us during and after
              registration, and you shall be responsible for all acts done
              through the use of your registered account on the Platform.
            </p>

            <p>
              Neither we nor any third parties provide any warranty or guarantee
              as to the accuracy, timeliness, performance, completeness or
              suitability of the information and materials offered on this
              website or through the Services, for any specific purpose. You
              acknowledge that such information and materials may contain
              inaccuracies or errors and we expressly exclude liability for any
              such inaccuracies or errors to the fullest extent permitted by
              law.
            </p>

            <p>
              Your use of our Services and the Platform is solely and entirely
              at your own risk and discretion for which we shall not be liable
              to you in any manner. You are required to independently assess and
              ensure that the Services meet your requirements.
            </p>
          </section>

          {/* 5. Intellectual Property */}
          <section className="space-y-3">
            <p>
              The contents of the Platform and the Services are proprietary to
              us and are licensed to us. You will not have any authority to
              claim any intellectual property rights, title, or interest in its
              contents. The contents include and are not limited to the design,
              layout, look and graphics.
            </p>

            <p>
              You acknowledge that unauthorized use of the Platform and/or the
              Services may lead to action against you as per these Terms of Use
              and/or applicable laws.
            </p>
          </section>

          {/* 6. Fees & Charges */}
          <section className="space-y-3">
            <p>
              You agree to pay us the charges associated with availing the
              Services.
            </p>
          </section>

          {/* 7. Prohibited Use */}
          <section className="space-y-3">
            <p>
              You agree not to use the Platform and/or Services for any purpose
              that is unlawful, illegal or forbidden by these Terms, or Indian
              or local laws that might apply to you.
            </p>
          </section>

          {/* 8. Third-Party Links */}
          <section className="space-y-3">
            <p>
              You agree and acknowledge that the website and the Services may
              contain links to other third party websites. On accessing these
              links, you will be governed by the terms of use, privacy policy
              and such other policies of such third party websites. These links
              are provided for your convenience to provide further information.
            </p>
          </section>

          {/* 9. Transactions */}
          <section className="space-y-3">
            <p>
              You understand that upon initiating a transaction for availing the
              Services you are entering into a legally binding and enforceable
              contract with the Platform Owner for the Services.
            </p>
          </section>

          {/* 10. Indemnity */}
          <section className="space-y-3">
            <p>
              You shall indemnify and hold harmless the Platform Owner, its
              affiliates, group companies (as applicable) and their respective
              officers, directors, agents, and employees, from any claim or
              demand, or actions including reasonable attorney&apos;s fees, made
              by any third party or penalty imposed due to or arising out of
              your breach of these Terms of Use, Privacy Policy and other
              Policies, or your violation of any law, rules or regulations or
              the rights (including infringement of intellectual property
              rights) of a third party.
            </p>
          </section>

          {/* 11. Force Majeure */}
          <section className="space-y-3">
            <p>
              Notwithstanding anything contained in these Terms of Use, the
              parties shall not be liable for any failure to perform an
              obligation under these Terms if performance is prevented or
              delayed by a force majeure event.
            </p>
          </section>

          {/* 12. Governing Law & Jurisdiction */}
          <section className="space-y-3">
            <p>
              These Terms and any dispute or claim relating to it, or its
              enforceability, shall be governed by and construed in accordance
              with the laws of India.
            </p>

            <p>
              All disputes arising out of or in connection with these Terms
              shall be subject to the exclusive jurisdiction of the courts in
              Vishakhapatnam, Andhra Pradesh.
            </p>
          </section>

          {/* 13. Contact */}
          <section className="space-y-3">
            <p>
              All concerns or communications relating to these Terms must be
              communicated to us using the contact information provided on this
              website.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
